### ISSUE TITLE
Open user are able to open picture in picture lyrics

### ISSUE THREAD

**Issue by MarcoMadera** [MarcoMadera/Rindu#241]
**Describe the bug**

**To Reproduce**
1. Play some music 
2. Picture in picture lyrics
3. See error 'You need a premium account to use this feature' while opening pip lyrics

**Expected behavior**
As open user only have 30 seconds music preview, the can't enjoy the full pip lyrics experience
Do not open the pip lyrics or hide pip lyrics button for open users

**Screenshots**
<img width="871" alt="image" src="https://github.com/MarcoMadera/Rindu/assets/17222523/27950303-8671-43bf-bd45-83b227b1048b">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Product: open
- Page: [e.g. /dashboard, playlist/{id}]

**Comment by mahimshridhar** [comment]
hi, can i take this?

**Comment by MarcoMadera** [comment]
@mahimshridhar Yes, you can take it 😁

**Comment by mahimshridhar** [comment]
i have raised a [pr](https://github.com/MarcoMadera/Rindu/pull/316), please let me know if any change is needed.

**Comment by MarcoMadera** [comment]
Thank you! @mahimshridhar 

There is also one more of these buttons in the lyrics normal view: https://github.com/MarcoMadera/Rindu/blob/b7aa5119104707e2e1a4afa3a5e0438a55d61505/components/FullScreenLyrics/FullScreenLyrics.tsx#L50

To access to it, you need to click the lyrics button next to this one
<img width="1259" alt="image" src="https://github.com/MarcoMadera/Rindu/assets/17222523/8d5073d5-ed26-4728-8bea-3d58ede20a78">

Or in full screen:
<img width="1259" alt="image" src="https://github.com/MarcoMadera/Rindu/assets/17222523/f08b4bb1-97e1-430a-b8db-9f9f251f5451">

<img width="1259" alt="image" src="https://github.com/MarcoMadera/Rindu/assets/17222523/8614e72b-548f-4540-bd34-17f1890fc0bb">

It is the same button for both views. My bad for not mentioning it. You can include it if you want or I can leave it for another issue

**Comment by mahimshridhar** [comment]
Sure updated in same PR.
